# Generated by Django 5.1.6 on 2025-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_pass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
