# Generated by Django 5.1.6 on 2025-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_rename_discription_foodlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='category',
            field=models.CharField(choices=[('Pure Veg', 'Pure Veg'), ('Non Veg', 'Non Veg'), ('Fast Food', 'Fast Food'), ('Sweets', 'Sweets'), ('Cake', 'Cake')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
