# Generated by Django 5.1.6 on 2025-02-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0005_alter_foodlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
