# Generated by Django 5.1.6 on 2025-02-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0006_alter_foodlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='category',
            field=models.CharField(choices=[('Pure Veg', 'Pure Veg'), ('Non Veg', 'Non Veg'), ('Fast Food', 'Fast Food'), ('Sweets', 'Sweets'), ('Cake', 'Cake')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
