# Generated by Django 5.1.6 on 2025-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0007_alter_foodlist_category_alter_foodlist_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_pass',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
