# Generated by Django 5.1.6 on 2025-02-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0008_remove_userdata_user_email_alter_foodlist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='category',
            field=models.CharField(choices=[('Pure Veg', 'Pure Veg'), ('Non Veg', 'Non Veg'), ('Fast Food', 'Fast Food'), ('Sweets', 'Sweets'), ('Cake', 'Cake')], max_length=100),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
