# Generated by Django 5.1.6 on 2025-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0009_alter_foodlist_category_alter_foodlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
