# Generated by Django 5.1.6 on 2025-02-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0010_alter_foodlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
