# Generated by Django 5.1.4 on 2025-02-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0011_alter_foodlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='user_pass',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
