# Generated by Django 5.1.5 on 2025-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0016_alter_userdata_email_alter_userdata_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
