# Generated by Django 5.1.5 on 2025-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0017_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='total',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
