# Generated by Django 5.1.5 on 2025-02-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0018_orderlist_city_orderlist_country_orderlist_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
